Task.create(title: 'ゴルフA')
Task.create(title: 'プログラミングA')
Task.create(title: 'ゴルフB')
Task.create(title: 'プログラミングB')
Task.create(title: 'ゴルフC')
Task.create(title: 'プログラミングC')
Task.create(title: 'ゴルフD')
Task.create(title: 'プログラミングD')